version: '2'

services:

  proxy:
    image: jwilder/nginx-proxy:alpine
    links:
      - registry
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /etc/nginx/certs
      - ./conf/proxy.conf:/etc/nginx/proxy.conf
    restart: 'always'

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - proxy

  registry:
    build: .
    restart: 'always'
    environment:
      - VIRTUAL_HOST=registry.js.ipfs.io
      - VIRTUAL_PORT=50321
      - LETSENCRYPT_HOST=registry.js.ipfs.io
      - LETSENCRYPT_EMAIL=alex@achingbrain.net
      - CLONE_EAGER_DOWNLOAD=false
      - CLONE=false
      - EXTERNAL_PROTOCOL=https
      - EXTERNAL_HOST=registry.js.ipfs.io
      - EXTERNAL_PORT=443
      - IPFS_FLUSH=true
      - STORE_TYPE=s3
      - STORE_S3_REGION=${STORE_S3_REGION}
      - STORE_S3_BUCKET=${STORE_S3_BUCKET}
      - STORE_S3_ACCESS_KEY_ID=${STORE_S3_ACCESS_KEY_ID}
      - STORE_S3_SECRET_ACCESS_KEY=${STORE_S3_SECRET_ACCESS_KEY}
